schema_version = "1.0.0"
id = "sketch_to_mesh"
name = "Sketch-To-Mesh"
tagline = "Converts sketch images into 3D mesh models using OpenCV"
version = "0.0.1"
blender_version_min = "4.2.0"
type = "add-on"
maintainer = "Judah, Kell, James, Rafael"
license = "Python-2.0"

# Additional URLs
wiki_url = "https://github.com/Klimentbehr/Sketch-To-Mesh#readme"
tracker_url = "https://github.com/Klimentbehr/Sketch-To-Mesh/issues"

# Other metadata
support = "COMMUNITY"
category = "Tool"
